directories:
  output: dist
  buildResources: build
appId: Hybridlauncher
productName: Hybrid Launcher
artifactName: ${productName}-setup-${version}.${ext}
copyright: Copyright © 2023 mc.hybrid.de
asar: true
compression: maximum
files:
  - filter:
      - '!{dist,.gitignore,.vscode,docs,dev-app-update.yml,.nvmrc,.eslintrc.json}'
extraResources:
  - filter:
      - libraries
win:
  target:
    - target: nsis
      arch: x64
nsis:
  oneClick: false
  perMachine: false
  allowElevation: true
  allowToChangeInstallationDirectory: true
mac:
  target:
    - target: dmg
      arch:
        - x64
        - arm64
  artifactName: ${productName}-setup-${version}-${arch}.${ext}
  category: public.app-category.games
linux:
  target: AppImage
  maintainer: Pascal0397
  vendor: Pascal0397
  synopsis: Modded Minecraft Launcher
  description: Custom launcher which allows users to join modded servers. All mods, configurations, and updates are handled automatically.
  category: Game
electronVersion: 24.5.1
